version: '3.8'

services:
  server:
    build: .
    container_name: 'friendspicker_server'
    volumes:
      - .:/var/www/project

  proxy:
    image: nginx:1.24-alpine3.17
    container_name: 'friendspicker_proxy'
    ports:
      - target: 80
        published: 8122
        protocol: tcp
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./public:/var/www/project
    depends_on:
      - server

networks:
  default:
    driver: bridge
