monolog:
    handlers:
        main:
            type: fingers_crossed
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            excluded_http_codes: [ 400, 403, 404 ]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
